version: '3'
services:
  flask:
    container_name: flask
    image: docker-image # cd.yml로 이미지 설정
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - VITO_CLIENT_ID=${VITO_CLIENT_ID}
      - VITO_CLIENT_SECRET=${VITO_CLIENT_SECRET}
    networks:
      - oreo

  redis:
    container_name: redis
    restart: always
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - oreo

networks:
  oreo:
    external: true