version: '3'
services:
  flask:
    container_name: flask
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - oreo

  redis:
    container_name: redis
    restart: always
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - oreo

networks:
  oreo:
    external: true